[versions]
kotlin = "2.2.21"
junit = "5.10.2"
okhttp="4.12.0"
spring-boot = "4.0.1"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
okhttp3-client = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
# plugin dependencies
plugin-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-spring = { module = "org.jetbrains.kotlin.plugin.spring:org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref = "kotlin" }

[bundles]
okhttp3 = ["okhttp3-client", "okhttp3-mockwebserver"]
plugins = ["plugin-kotlin-gradle", "plugin-kotlin-spring"]
